######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 10 21:59:05 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += networkinformation.h
SOURCES += main.cpp networkinformation.cpp
TRANSLATIONS += networkinformation_zh.ts
QT += network
