######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:23:06 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += digiclock.h
SOURCES += digiclock.cpp main.cpp
