######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:52:38 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
